yarnPath: .yarn/releases/yarn-4.10.3.cjs

# Enable Plug'n'Play instead of node_modules
nodeLinker: pnp

# Global cache disabled for project-local control
enableGlobalCache: false

# Lock down installs
enableImmutableInstalls: true

# Block npm, pnpm, bun usage
supportedArchitectures:
  os: [current]
  cpu: [current]
  libc: [current]
enableScripts: true

# Optional: custom message if someone tries npm install
npmRegistryServer: "https://registry.yarnpkg.com"

